### ISSUE TITLE
Notebook broken

### ISSUE THREAD

**Issue by dillfrescott** [eloimoliner/CQTdiff#1]
Something is wrong with the json I think

**Comment by eloimoliner** [comment]
There was a little typo in the link. I hope that solves the problem. Did you find some other error that made you think there was a problem with the json?

**Comment by jreoka** [comment]
Yes. Google colab seems to not like it very much haha. It says it's corrupted or something.

I can try again in a bit and see if maybe it was just a glitch.

**Comment by eloimoliner** [comment]
Oh, that's strange. Could you please try now? It seems to work for me.

**Comment by jreoka** [comment]
It works now! Cool!
